---
title: "Modelos de Transicion de Markov"
output: html_document
---

### CARGA DE DATOS

```{r}

if (!require("curl")) {
   install.packages("curl", repos="http://cran.rstudio.com/") 
   library("curl")
}
 
eleccion.marca <- read.csv(curl("https://raw.githubusercontent.com/joaquinsanchez/LibroEP/master/Cap_6/pub_eleccion.csv"), sep = ",")

if (!require("dplyr")) {
   install.packages("dplyr", repos="http://cran.rstudio.com/") 
   library("dplyr")
}

eleccion.marca <- select(eleccion.marca, -X)

```

### ANALISIS DESCRIPTIVO

```{r}

if (!require("psych")) {
   install.packages("psych", repos="http://cran.rstudio.com/") 
   library("psych")
}

describeBy(eleccion.marca, group = "marca")
describe(eleccion.marca)

```

### MODELO DE EFECTOS FIJOS (no tiene en cuenta la estructura de panel)

```{r}

if (!require("mlogit")) {
   install.packages("mlogit", repos="http://cran.rstudio.com/") 
   library("mlogit")
}

prep.logit <- mlogit.data(eleccion.marca, id="id", choice="marca", shape="wide", varying = c(3:9), sep="_")

mod.2 <- mlogit(marca ~ pubac | 0, prep.logit, print.level=0)
summary(mod.2) 

```

### ELASTICIDAD Y SENSIBILIDAD

```{r}

# Elasticidades directas y cruzadas

z1 <- with(prep.logit, data.frame(pubac = tapply(pubac, index(mod.2)$alt, mean)))

elasticidad <- effects(mod.2, covariate = "pubac",  data = z1)
predict(mod.2, z1)
elasticidad

# Sensibilidad (Marca "A" reduce su inversion a la mitad)

z2<-z1
z3<-z1
z4<-z1
z5<-z1
z6<-z1
z7<-z1
z8<-z1
z9<-z1
z10<-z1
z11<-z1
z12<-z1
z13<-z1
z14<-z1
z15<-z1
z16<-z1
z17<-z1
z18<-z1
z19<-z1
z20<-z1
z21<-z1 

z2[1,1]<-0
z3[1,1]<-1
z4[1,1]<-2
z5[1,1]<-3
z6[1,1]<-4
z7[1,1]<-5
z8[1,1]<-6
z9[1,1]<-7
z10[1,1]<-8
z11[1,1]<-9
z12[1,1]<-10
z13[1,1]<-11
z14[1,1]<-12
z15[1,1]<-13
z16[1,1]<-14
z17[1,1]<-15
z18[1,1]<-16
z19[1,1]<-17
z20[1,1]<-18
z21[1,1]<-19

effects(mod.2, covariate = "pubac", type = "rr", data = z1)
effects(mod.2, covariate = "pubac", type = "rr", data = z2)
effects(mod.2, covariate = "pubac", type = "rr", data = z3)
effects(mod.2, covariate = "pubac", type = "rr", data = z4)
effects(mod.2, covariate = "pubac", type = "rr", data = z5)
effects(mod.2, covariate = "pubac", type = "rr", data = z6)
effects(mod.2, covariate = "pubac", type = "rr", data = z7)
effects(mod.2, covariate = "pubac", type = "rr", data = z8)
effects(mod.2, covariate = "pubac", type = "rr", data = z9)
effects(mod.2, covariate = "pubac", type = "rr", data = z10)
effects(mod.2, covariate = "pubac", type = "rr", data = z11)
effects(mod.2, covariate = "pubac", type = "rr", data = z12)
effects(mod.2, covariate = "pubac", type = "rr", data = z13)
effects(mod.2, covariate = "pubac", type = "rr", data = z14)
effects(mod.2, covariate = "pubac", type = "rr", data = z15)
effects(mod.2, covariate = "pubac", type = "rr", data = z16)
effects(mod.2, covariate = "pubac", type = "rr", data = z17)
effects(mod.2, covariate = "pubac", type = "rr", data = z18)
effects(mod.2, covariate = "pubac", type = "rr", data = z19)
effects(mod.2, covariate = "pubac", type = "rr", data = z20)

p1<-as.data.frame(predict(mod.2, z1))
p2<-as.data.frame(predict(mod.2, z2))
p3<-as.data.frame(predict(mod.2, z3))
p4<-as.data.frame(predict(mod.2, z4))
p5<-as.data.frame(predict(mod.2, z5))
p6<-as.data.frame(predict(mod.2, z6))
p7<-as.data.frame(predict(mod.2, z7))
p8<-as.data.frame(predict(mod.2, z8))
p9<-as.data.frame(predict(mod.2, z9))
p10<-as.data.frame(predict(mod.2, z10))
p11<-as.data.frame(predict(mod.2, z11))
p12<-as.data.frame(predict(mod.2, z12))
p13<-as.data.frame(predict(mod.2, z13))
p14<-as.data.frame(predict(mod.2, z14))
p15<-as.data.frame(predict(mod.2, z15))
p16<-as.data.frame(predict(mod.2, z16))
p17<-as.data.frame(predict(mod.2, z17))
p18<-as.data.frame(predict(mod.2, z18))
p19<-as.data.frame(predict(mod.2, z19))
p20<-as.data.frame(predict(mod.2, z20))
                   
sensib.2 <- cbind(p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20)  
colnames(sensib.2) <- paste(seq(0,18,1))

# Grafico de sensibilidad de la marca A

barplot(as.matrix(sensib.2), xlab = "Numero de Exposiciones Acumuladas hasta el acto de compra (Marca A)", ylab="Cuota de mercado estimada", col=gray.colors(7), legend.text = TRUE) 

```
